AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: DeployNodeJsApplication
      RoleArn: "arn:aws:iam::211125671700:role/service-role/AWSCodePipelineServiceRole-eu-north-1-DeployNodeJsApplication"
      ArtifactStore:
        Type: S3
        Location: codepipeline-eu-north-1-107886998537
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                BranchName: main
                ConnectionArn: "arn:aws:codestar-connections:eu-north-1:211125671700:connection/ef4e9c28-ec04-447c-b481-233738ef37f1"
                DetectChanges: "true"
                FullRepositoryId: majorzsolti/sample-nodejs-fork
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceArtifact
              InputArtifacts: []
              Region: eu-north-1
              Namespace: SourceVariables
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ElasticBeanstalk
                Version: '1'
              Configuration:
                ApplicationName: elasticBeanstalk
                EnvironmentName: ElasticBeanstalk-env
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts: []
              Region: eu-north-1
              Namespace: DeployVariables
      Version: 1
      ExecutionMode: QUEUED
      PipelineType: V2
  MyPipelineArtifactStoreBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: codepipeline-eu-north-1-107886998537
      PolicyDocument:
        Statement:
          - Sid: AllowPipelineAccess
            Effect: Allow
            Principal:
              Service: "codepipeline.amazonaws.com"
            Action: "s3:GetBucketVersioning"
            Resource: "arn:aws:s3:::codepipeline-eu-north-1-107886998537"
          - Sid: AllowPipelineObjectAccess
            Effect: Allow
            Principal:
              Service: "codepipeline.amazonaws.com"
            Action:
              - "s3:GetObject"
              - "s3:GetObjectVersion"
              - "s3:GetObjectVersionTagging"
            Resource: "arn:aws:s3:::codepipeline-eu-north-1-107886998537/*"
